config/routes.rb
Rails.application.routes.draw do



  authenticated :user do
    root 'users#show', as: :authenticated
  end
  resources :users, only: [] do
    resources :items, only: [:create, :destroy]

  end
  resources :items, only: [] do
    resources :subitems, only: [:create]
    post 'subitems/:id/mark_complete' => 'subitems#mark_complete', as: :mark_complete
    post 'subitems/:id/mark_incomplete' => 'subitems#mark_incomplete', as: :mark_incomplete
  end
  devise_for :users
  root to: 'welcome#about'

  namespace :api, defaults: { format: :json } do
    devise_for :users, controllers: {sessions: "users/sessions"}
    resources :users, only: [:index, :show] do
      resources :items, only: [:create, :destroy, :update]
    end
    resources :items, only: [] do
      resources :subitems, only: [:create, :update]
      patch 'subitems/:id/mark_complete' => 'subitems#mark_complete'
      patch 'subitems/:id/mark_incomplete' => 'subitems#mark_incomplete'
    end
  end

end

app/models/subitem.rb
class Subitem < ActiveRecord::Base
  belongs_to :item
  default_scope { order("completed, updated_at")}
  validates :name, length: {minimum: 3}, presence: true
  validates :item, presence: true
end

app/controllers/api/subitems_controller.rb
class Api::SubitemsController < ApiController
  before_action :authenticate_user!

  def create
    item = Item.find(params[:item_id])
    subitem = item.subitems.new(subitem_params)
    if subitem.save
      render json: subitem
    else
      render json: { errors: subitem.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    subitem = Subitem.find(params[:id])
    if subitem.update(subitem_params)
      render json: subitem
    else
      render json: {errors: subitem.errors.full_messages}, status: :unprocessable_entity
    end
  end

  def mark_complete
    subitem = Subitem.find(params[:id])
    if subitem.update_attribute(:completed, true)
      render json: subitem, serializer: SubitemSerializer
    else
      render json: { error: "Subitem not updated, alter request"}, status: 400
    end
  end

  def mark_incomplete
    subitem = Subitem.find(params[:id])
    if subitem.update_attribute(:completed, false)
      render json: subitem, serializer: SubitemSerializer
    else
      render json: { error: "Subitem not updated, alter request"}, status: 400
    end
  end

  private
  def subitem_params
    params.require(:subitem).permit(:name, :completed)
  end
end

app/controllers/subitems_controller.rb
class SubitemsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @subitem = @item.subitems.new(subitem_params)

    if @subitem.save
      @new_subitem = @item.subitems.new
      flash[:notice] = "Subitem for #{@item.name} created."
    else
      flash[:error] = "There was an error creating subitem."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def mark_complete
    @subitem = Subitem.find(params[:id])
    if @subitem.update_attribute(:completed, true)
      @item_completed = reveal_delete_item_button?(@subitem.item)
      flash[:notice] = "#{@subitem.name} completed"
    else
      flash[:error] = "There was an error. Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def mark_incomplete
    @subitem = Subitem.find(params[:id])
    if @subitem.update_attribute(:completed, false)
      flash[:notice] = "#{@subitem.name} marked incomplete."
    else
      flash[:error] = "There was an error. Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def subitem_params
    params.require(:subitem).permit(:name)
  end

  def reveal_delete_item_button?(item)
    item.subitems.all?{|s| s.completed == true}
  end
end

app/helpers/subitems_helper.rb
module SubitemsHelper
end

app/views/subitems/_form.html.haml
.form-inline
  = form_for [item, subitem], remote: true do |f|
    .form-group
      = f.text_field :name, class: 'form-control', placeholder: "Create subitem"
    .form-group
      = f.submit "Save", class: 'btn btn-primary'

app/views/subitems/_subitem.html.haml
= content_tag :div, class: 'list-group-item', id: "subitem-#{subitem.id}" do
  - if subitem.completed == false
    = link_to "", item_mark_complete_path(subitem.item, subitem), class: 'glyphicon glyphicon-unchecked', method: :post, remote: true
  - else
    = link_to "", item_mark_incomplete_path(subitem.item, subitem), class: 'glyphicon glyphicon-ok', method: :post, remote: true
  = subitem.name

app/views/subitems/create.js.erb
<% if @subitem.valid? %>
  $('#js-subitems-'+<%= @item.id %>).append("<%= escape_javascript(render(@subitem))%>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
  $('#new-subitem-' +<%= @item.id %>).html("<%= escape_javascript(render partial: 'subitems/form', locals: {item: @item, subitem: @new_subitem})%>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
  $('#new-subitem-' +<%= @item.id %>).html("<%= escape_javascript(render partial: 'subitems/form', locals: {item: @item, subitem: @new_subitem})%>")
<% end %>
if($('#name-' +<%= @subitem.item.id %>).find('.glyphicon.glyphicon-remove-sign').length){

  $('#delete-' + <%= @subitem.item.id %>).remove();
}

app/views/subitems/mark_complete.js.erb
<% if @subitem.completed %>
  $('#subitem-' +<%= @subitem.id %>).remove();
  $('#js-subitems-' +<%= @subitem.item.id %>).append("<%= escape_javascript(render(@subitem))%>");
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %>");
<% else %>
  ('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %>");
<% end %>
<% if @item_completed %>
  $('#name-' +<%= @subitem.item.id %>).prepend("<%= escape_javascript(link_to "", [current_user, @subitem.item], method: :delete, class: 'glyphicon glyphicon-remove-sign',id: "delete-#{@subitem.item.id}" ,remote: true) %>");
<% end %>

app/views/subitems/mark_incomplete.js.erb
<% if !@subitem.completed %>
  $('#subitem-' +<%= @subitem.id %>).remove();
  $('#js-subitems-' +<%= @subitem.item.id %>).prepend("<%= escape_javascript(render(@subitem))%>");
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %>")
  if($('#name-' +<%= @subitem.item.id %>).find('.glyphicon.glyphicon-remove-sign').length){

    $('#delete-' + <%= @subitem.item.id %>).remove();
  }
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %>")
<% end %>