config/routes.rb
Rails.application.routes.draw do



  authenticated :user do
    root 'users#show', as: :authenticated
  end
  resources :users, only: [] do
    resources :items, only: [:create, :destroy]

  end
  resources :items, only: [] do
    resources :subitems, only: [:create]
    post 'subitems/:id/mark_complete' => 'subitems#mark_complete', as: :mark_complete
    post 'subitems/:id/mark_incomplete' => 'subitems#mark_incomplete', as: :mark_incomplete
  end
  devise_for :users
  root to: 'welcome#about'

  namespace :api, defaults: { format: :json } do
    devise_for :users, controllers: {sessions: "users/sessions"}
    resources :users, only: [:index, :show] do
      resources :items, only: [:create, :destroy, :update]
    end
    resources :items, only: [] do
      resources :subitems, only: [:create, :update]
      patch 'subitems/:id/mark_complete' => 'subitems#mark_complete'
      patch 'subitems/:id/mark_incomplete' => 'subitems#mark_incomplete'
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :subitems, dependent: :destroy
  default_scope { order(created_at: :desc)}
  validates :name, length: {minimum: 3}, presence: true
  validates :user, presence: true
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController
  before_action :authenticate_user!

  def create
    user = User.find(params[:user_id])
    item = user.items.new(item_params)
    if item.save
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      render json: item
    else
      render json: {errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      user = User.find(params[:user_id])
      item = user.items.find(params[:id])
      if can_be_deleted?(item)
        item.destroy
        render json: {message: "Item has been deleted"}.to_json, status: :ok
      else
        render json: {error: "This item cannot be deleted because it has incomplete subitems"}, status: 403
      end
    rescue ActiveRecord::RecordNotFound
      render json: {}.to_json, status: :not_found
    end

  end

  private
  def can_be_deleted?(item)
    item.subitems == [] || item.subitems.all?{|s| s.completed == true}
  end
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  def create
    @user = User.find(params[:user_id])
    @item = @user.items.new(item_params)

    if @item.save
      @new_item = @user.items.new
      flash[:notice] = "Item added."
    else
      flash[:error] = "Item creation failed."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:id])
    if @item.destroy
      flash[:notice] = "#{@item.name} completed"
    else
      flash[:error] = "There was an error marking the item as complete. Please try again."
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def mark_complete
    @item = item
    @item.mark_complete!
    flash[:notice] = "Item completed"
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def item
    current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def can_be_deleted?(item)
    item.subitems.all?{|s| s.completed == true} || item.subitems == []
  end
end

app/views/items/_form.html.haml
%h3 New Item:
= form_for [user, item], remote: true do |f|
  .form-group
    = f.text_field :name, class: 'form-control', placeholder: "Enter item here"
  .form-group
    = f.submit "Save", class: 'btn btn-success'

app/views/items/_item.html.haml
= content_tag :div, class: 'media', id: "item-#{item.id}" do
  .media-body
    %p
      - if item.completed?
        %i.glyphicon.glyphicon-ok.complete
      - else
        = link_to "", mark_complete_user_item_path(current_user, item), method: :post, class: 'glyphicon glyphicon-ok incomplete', remote: true
      = item.name
    %small
      created:
      = time_ago_in_words(item.created_at)
      ago --
      = distance_of_time_in_words(Time.now, item.created_at + 7.days)
      to complete item

app/views/items/create.js.erb
<% if @item.valid? %>
  $('.js-items').prepend("<%= escape_javascript(render(@item))%>");
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: {user: @user, item: @new_item})%>");
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: {user: @user, item: @item})%>")
<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).hide();
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>")
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class'close' data-dismiss='alert'>&times;</button><%= flash[:error]%></div>");
<% end %>

app/views/items/mark_complete.js.erb
<% if @item.completed? %>
  $("#item-" + <%= @item.id %> + " .media-body a").removeClass('incomplete').addClass('complete');
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>")
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class'close' data-dismiss='alert'>&times;</button><%= flash[:error]%></div>");
<% end %>